export const colorSchemes = {
  normal: {
    primary: 'from-orange-500 to-amber-500',
    primaryHover: 'from-orange-600 to-amber-600',
    primaryBg: 'bg-orange-500',
    primaryText: 'text-orange-600',
    primaryBorder: 'border-orange-200',
    primaryLight: 'bg-orange-50',
    accent: 'bg-amber-400',
    gradient: 'from-orange-50 via-amber-50 to-yellow-50',
  },
  protanopia: {
    primary: 'from-blue-600 to-cyan-600',
    primaryHover: 'from-blue-700 to-cyan-700',
    primaryBg: 'bg-blue-600',
    primaryText: 'text-blue-700',
    primaryBorder: 'border-blue-300',
    primaryLight: 'bg-blue-50',
    accent: 'bg-cyan-500',
    gradient: 'from-blue-50 via-cyan-50 to-teal-50',
  },
  deuteranopia: {
    primary: 'from-blue-600 to-purple-600',
    primaryHover: 'from-blue-700 to-purple-700',
    primaryBg: 'bg-blue-600',
    primaryText: 'text-blue-700',
    primaryBorder: 'border-blue-300',
    primaryLight: 'bg-blue-50',
    accent: 'bg-purple-500',
    gradient: 'from-blue-50 via-purple-50 to-indigo-50',
  },
  tritanopia: {
    primary: 'from-pink-600 to-rose-600',
    primaryHover: 'from-pink-700 to-rose-700',
    primaryBg: 'bg-pink-600',
    primaryText: 'text-pink-700',
    primaryBorder: 'border-pink-300',
    primaryLight: 'bg-pink-50',
    accent: 'bg-rose-500',
    gradient: 'from-pink-50 via-rose-50 to-red-50',
  },
  monochrome: {
    primary: 'from-gray-700 to-gray-900',
    primaryHover: 'from-gray-800 to-black',
    primaryBg: 'bg-gray-800',
    primaryText: 'text-gray-900',
    primaryBorder: 'border-gray-400',
    primaryLight: 'bg-gray-100',
    accent: 'bg-gray-600',
    gradient: 'from-gray-50 via-gray-100 to-gray-200',
  },
};

export const categoryColors = {
  normal: {
    all: { bg: 'bg-orange-500', text: 'text-orange-600', light: 'bg-orange-50' },
    meals: { bg: 'bg-amber-500', text: 'text-amber-600', light: 'bg-amber-50' },
    world: { bg: 'bg-red-500', text: 'text-red-600', light: 'bg-red-50' },
    occasion: { bg: 'bg-pink-500', text: 'text-pink-600', light: 'bg-pink-50' },
    diet: { bg: 'bg-green-500', text: 'text-green-600', light: 'bg-green-50' },
    difficulty: { bg: 'bg-blue-500', text: 'text-blue-600', light: 'bg-blue-50' },
    seasonal: { bg: 'bg-emerald-500', text: 'text-emerald-600', light: 'bg-emerald-50' },
    quick: { bg: 'bg-orange-600', text: 'text-orange-700', light: 'bg-orange-100' },
  },
  protanopia: {
    all: { bg: 'bg-blue-600', text: 'text-blue-700', light: 'bg-blue-50' },
    meals: { bg: 'bg-cyan-600', text: 'text-cyan-700', light: 'bg-cyan-50' },
    world: { bg: 'bg-teal-600', text: 'text-teal-700', light: 'bg-teal-50' },
    occasion: { bg: 'bg-sky-600', text: 'text-sky-700', light: 'bg-sky-50' },
    diet: { bg: 'bg-indigo-600', text: 'text-indigo-700', light: 'bg-indigo-50' },
    difficulty: { bg: 'bg-violet-600', text: 'text-violet-700', light: 'bg-violet-50' },
    seasonal: { bg: 'bg-blue-700', text: 'text-blue-800', light: 'bg-blue-100' },
    quick: { bg: 'bg-cyan-700', text: 'text-cyan-800', light: 'bg-cyan-100' },
  },
  deuteranopia: {
    all: { bg: 'bg-blue-600', text: 'text-blue-700', light: 'bg-blue-50' },
    meals: { bg: 'bg-purple-600', text: 'text-purple-700', light: 'bg-purple-50' },
    world: { bg: 'bg-indigo-600', text: 'text-indigo-700', light: 'bg-indigo-50' },
    occasion: { bg: 'bg-violet-600', text: 'text-violet-700', light: 'bg-violet-50' },
    diet: { bg: 'bg-fuchsia-600', text: 'text-fuchsia-700', light: 'bg-fuchsia-50' },
    difficulty: { bg: 'bg-blue-700', text: 'text-blue-800', light: 'bg-blue-100' },
    seasonal: { bg: 'bg-purple-700', text: 'text-purple-800', light: 'bg-purple-100' },
    quick: { bg: 'bg-indigo-700', text: 'text-indigo-800', light: 'bg-indigo-100' },
  },
  tritanopia: {
    all: { bg: 'bg-pink-600', text: 'text-pink-700', light: 'bg-pink-50' },
    meals: { bg: 'bg-rose-600', text: 'text-rose-700', light: 'bg-rose-50' },
    world: { bg: 'bg-red-600', text: 'text-red-700', light: 'bg-red-50' },
    occasion: { bg: 'bg-fuchsia-600', text: 'text-fuchsia-700', light: 'bg-fuchsia-50' },
    diet: { bg: 'bg-pink-700', text: 'text-pink-800', light: 'bg-pink-100' },
    difficulty: { bg: 'bg-rose-700', text: 'text-rose-800', light: 'bg-rose-100' },
    seasonal: { bg: 'bg-red-700', text: 'text-red-800', light: 'bg-red-100' },
    quick: { bg: 'bg-pink-800', text: 'text-pink-900', light: 'bg-pink-200' },
  },
  monochrome: {
    all: { bg: 'bg-gray-800', text: 'text-gray-900', light: 'bg-gray-100' },
    meals: { bg: 'bg-gray-700', text: 'text-gray-800', light: 'bg-gray-50' },
    world: { bg: 'bg-gray-600', text: 'text-gray-700', light: 'bg-gray-100' },
    occasion: { bg: 'bg-gray-500', text: 'text-gray-600', light: 'bg-gray-50' },
    diet: { bg: 'bg-gray-900', text: 'text-black', light: 'bg-gray-200' },
    difficulty: { bg: 'bg-black', text: 'text-gray-900', light: 'bg-gray-100' },
    seasonal: { bg: 'bg-gray-700', text: 'text-gray-800', light: 'bg-gray-50' },
    quick: { bg: 'bg-gray-800', text: 'text-gray-900', light: 'bg-gray-100' },
  },
};
